PAdES Electronic Signature: gui.SignatureAppWindow Class Reference
gui.SignatureAppWindow Class Reference
Public Member Functions
__init__ (self, usb_detector)
handle_usb_connected (self, usb_path, encrypted_key_data)
handle_usb_disconnected (self)
handle_status_update (self, message)
setup_sign_tab (self)
handle_pin_input (self)
sign_document (self)
setup_verify_tab (self)
browse_pdf (self)
browse_output (self)
browse_signed_pdf (self)
browse_public_key (self)
verify_signature (self)
Public Attributes
usb_detector = usb_detector
handle_usb_connected
handle_usb_disconnected
handle_status_update
tabs = QTabWidget()
sign_tab = QWidget()
verify_tab = QWidget()
status_layout = QHBoxLayout()
key_status = QLabel("Key Status: Not Loaded")
usb_status = QLabel("USB Status: No USB with key detected")
private_key = None
current_usb_path = None
encrypted_key_data = None
pdf_label = QLabel("Select PDF to sign:")
pdf_path = QLineEdit()
pdf_browse = QPushButton("Browse")
browse_pdf
private_key_label = QLabel("Private key location:")
private_key_path = QLineEdit()
pin_label = QLabel("Enter PIN:")
pin_input = QLineEdit()
handle_pin_input
output_label = QLabel("Save signed PDF as:")
output_path = QLineEdit()
output_browse = QPushButton("Browse")
browse_output
sign_button = QPushButton("Sign Document")
sign_document
progress_bar = QProgressBar()
signed_pdf_label = QLabel("Select signed PDF to verify:")
signed_pdf_path = QLineEdit()
signed_pdf_browse = QPushButton("Browse")
browse_signed_pdf
public_key_label = QLabel("Select public key file:")
public_key_path = QLineEdit()
public_key_browse = QPushButton("Browse")
browse_public_key
verify_button = QPushButton("Verify Signature")
verify_signature
verification_result = QLabel("")
Detailed Description
Main window for the PAdES signature application.
Definition at line 13 of file gui.py.
Constructor & Destructor Documentation
__init__()
gui.SignatureAppWindow.__init__ (self, usb_detector)
Definition at line 17 of file gui.py.
References __init__().
Referenced by __init__().
Member Function Documentation
browse_output()
gui.SignatureAppWindow.browse_output (self)
Open file dialog to select output location for signed PDF.
Definition at line 298 of file gui.py.
References output_path.
browse_pdf()
gui.SignatureAppWindow.browse_pdf (self)
Open file dialog to select PDF document to sign.
Definition at line 287 of file gui.py.
References output_path, and pdf_path.
browse_public_key()
gui.SignatureAppWindow.browse_public_key (self)
Open file dialog to select public key file.
Definition at line 317 of file gui.py.
References public_key_path, and verification_result.
browse_signed_pdf()
gui.SignatureAppWindow.browse_signed_pdf (self)
Open file dialog to select signed PDF document to verify.
Definition at line 308 of file gui.py.
References signed_pdf_path, and verification_result.
handle_pin_input()
gui.SignatureAppWindow.handle_pin_input (self)
Handle PIN input changes.
Definition at line 174 of file gui.py.
References output_path, pdf_path, pin_input, and sign_button.
handle_status_update()
gui.SignatureAppWindow.handle_status_update (self, message)
Handle status updates from USB detector.
Args:
    message (str): Status message
Definition at line 103 of file gui.py.
handle_usb_connected()
gui.SignatureAppWindow.handle_usb_connected (self, usb_path, encrypted_key_data)
Handle USB drive connection with private key.
Args:
    usb_path (str): Path to the USB drive
    encrypted_key_data (bytes): Encrypted private key data
Definition at line 63 of file gui.py.
References current_usb_path, encrypted_key_data, private_key_path, and usb_status.
handle_usb_disconnected()
gui.SignatureAppWindow.handle_usb_disconnected (self)
Handle USB drive disconnection.
Definition at line 84 of file gui.py.
References current_usb_path, encrypted_key_data, key_status, private_key, private_key_path, and usb_status.
setup_sign_tab()
gui.SignatureAppWindow.setup_sign_tab (self)
Setup the sign document tab.
Definition at line 113 of file gui.py.
References sign_tab.
setup_verify_tab()
gui.SignatureAppWindow.setup_verify_tab (self)
Setup the verify signature tab.
Definition at line 242 of file gui.py.
References verify_tab.
sign_document()
gui.SignatureAppWindow.sign_document (self)
Sign the selected PDF document.
Definition at line 183 of file gui.py.
References current_usb_path, encrypted_key_data, key_status, output_path, pdf_path, pin_input, and progress_bar.
verify_signature()
gui.SignatureAppWindow.verify_signature (self)
Verify the signature of the selected PDF document.
Definition at line 326 of file gui.py.
References public_key_path, signed_pdf_path, and verification_result.
Member Data Documentation
browse_output
gui.SignatureAppWindow.browse_output
Definition at line 146 of file gui.py.
browse_pdf
gui.SignatureAppWindow.browse_pdf
Definition at line 124 of file gui.py.
browse_public_key
gui.SignatureAppWindow.browse_public_key
Definition at line 264 of file gui.py.
browse_signed_pdf
gui.SignatureAppWindow.browse_signed_pdf
Definition at line 253 of file gui.py.
current_usb_path
gui.SignatureAppWindow.current_usb_path = None
Definition at line 60 of file gui.py.
Referenced by handle_usb_connected(), handle_usb_disconnected(), and sign_document().
encrypted_key_data
gui.SignatureAppWindow.encrypted_key_data = None
Definition at line 61 of file gui.py.
Referenced by handle_usb_connected(), handle_usb_disconnected(), and sign_document().
handle_pin_input
gui.SignatureAppWindow.handle_pin_input
Definition at line 139 of file gui.py.
handle_status_update
gui.SignatureAppWindow.handle_status_update
Definition at line 28 of file gui.py.
handle_usb_connected
gui.SignatureAppWindow.handle_usb_connected
Definition at line 26 of file gui.py.
handle_usb_disconnected
gui.SignatureAppWindow.handle_usb_disconnected
Definition at line 27 of file gui.py.
key_status
gui.SignatureAppWindow.key_status = QLabel("Key Status: Not Loaded")
Definition at line 49 of file gui.py.
Referenced by handle_usb_disconnected(), and sign_document().
output_browse
gui.SignatureAppWindow.output_browse = QPushButton("Browse")
Definition at line 145 of file gui.py.
output_label
gui.SignatureAppWindow.output_label = QLabel("Save signed PDF as:")
Definition at line 142 of file gui.py.
output_path
gui.SignatureAppWindow.output_path = QLineEdit()
Definition at line 143 of file gui.py.
Referenced by browse_output(), browse_pdf(), handle_pin_input(), and sign_document().
pdf_browse
gui.SignatureAppWindow.pdf_browse = QPushButton("Browse")
Definition at line 123 of file gui.py.
pdf_label
gui.SignatureAppWindow.pdf_label = QLabel("Select PDF to sign:")
Definition at line 120 of file gui.py.
pdf_path
gui.SignatureAppWindow.pdf_path = QLineEdit()
Definition at line 121 of file gui.py.
Referenced by browse_pdf(), handle_pin_input(), and sign_document().
pin_input
gui.SignatureAppWindow.pin_input = QLineEdit()
Definition at line 137 of file gui.py.
Referenced by key_generator.gui.KeyGeneratorWindow.generate_keys(), handle_pin_input(), and sign_document().
pin_label
gui.SignatureAppWindow.pin_label = QLabel("Enter PIN:")
Definition at line 136 of file gui.py.
private_key
gui.SignatureAppWindow.private_key = None
Definition at line 59 of file gui.py.
Referenced by handle_usb_disconnected().
private_key_label
gui.SignatureAppWindow.private_key_label = QLabel("Private key location:")
Definition at line 131 of file gui.py.
private_key_path
gui.SignatureAppWindow.private_key_path = QLineEdit()
Definition at line 132 of file gui.py.
Referenced by key_generator.gui.KeyGeneratorWindow.browse_private_key(), key_generator.gui.KeyGeneratorWindow.generate_keys(), handle_usb_connected(), and handle_usb_disconnected().
progress_bar
gui.SignatureAppWindow.progress_bar = QProgressBar()
Definition at line 158 of file gui.py.
Referenced by sign_document().
public_key_browse
gui.SignatureAppWindow.public_key_browse = QPushButton("Browse")
Definition at line 263 of file gui.py.
public_key_label
gui.SignatureAppWindow.public_key_label = QLabel("Select public key file:")
Definition at line 260 of file gui.py.
public_key_path
gui.SignatureAppWindow.public_key_path = QLineEdit()
Definition at line 261 of file gui.py.
Referenced by browse_public_key(), key_generator.gui.KeyGeneratorWindow.browse_public_key(), key_generator.gui.KeyGeneratorWindow.generate_keys(), and verify_signature().
sign_button
gui.SignatureAppWindow.sign_button = QPushButton("Sign Document")
Definition at line 153 of file gui.py.
Referenced by handle_pin_input().
sign_document
gui.SignatureAppWindow.sign_document
Definition at line 154 of file gui.py.
sign_tab
gui.SignatureAppWindow.sign_tab = QWidget()
Definition at line 37 of file gui.py.
Referenced by setup_sign_tab().
signed_pdf_browse
gui.SignatureAppWindow.signed_pdf_browse = QPushButton("Browse")
Definition at line 252 of file gui.py.
signed_pdf_label
gui.SignatureAppWindow.signed_pdf_label = QLabel("Select signed PDF to verify:")
Definition at line 249 of file gui.py.
signed_pdf_path
gui.SignatureAppWindow.signed_pdf_path = QLineEdit()
Definition at line 250 of file gui.py.
Referenced by browse_signed_pdf(), and verify_signature().
status_layout
gui.SignatureAppWindow.status_layout = QHBoxLayout()
Definition at line 48 of file gui.py.
tabs
gui.SignatureAppWindow.tabs = QTabWidget()
Definition at line 36 of file gui.py.
usb_detector
gui.SignatureAppWindow.usb_detector = usb_detector
Definition at line 23 of file gui.py.
usb_status
gui.SignatureAppWindow.usb_status = QLabel("USB Status: No USB with key detected")
Definition at line 50 of file gui.py.
Referenced by handle_usb_connected(), and handle_usb_disconnected().
verification_result
gui.SignatureAppWindow.verification_result = QLabel("")
Definition at line 275 of file gui.py.
Referenced by browse_public_key(), browse_signed_pdf(), and verify_signature().
verify_button
gui.SignatureAppWindow.verify_button = QPushButton("Verify Signature")
Definition at line 271 of file gui.py.
verify_signature
gui.SignatureAppWindow.verify_signature
Definition at line 272 of file gui.py.
verify_tab
gui.SignatureAppWindow.verify_tab = QWidget()
Definition at line 38 of file gui.py.
Referenced by setup_verify_tab().
The documentation for this class was generated from the following file:
signature_app/gui.py