PAdES Electronic Signature: usb_detector.USBDetector Class Reference
usb_detector.USBDetector Class Reference
Public Member Functions
__init__ (self)
run (self)
check_drive_for_key (self, drive_path)
get_removable_drives (self)
stop_monitoring (self)
start_monitoring (self)
Public Attributes
bool running = True
str system = platform.system()
connected_drives = self.get_removable_drives()
Static Public Attributes
usb_connected = pyqtSignal(str, bytes)
usb_disconnected = pyqtSignal()
status_update = pyqtSignal(str)
Detailed Description
Thread for monitoring USB drive connections and disconnections.
Automatically detects and loads private keys from USB drives.
Definition at line 11 of file usb_detector.py.
Constructor & Destructor Documentation
__init__()
usb_detector.USBDetector.__init__ (self)
Definition at line 20 of file usb_detector.py.
References __init__().
Referenced by __init__().
Member Function Documentation
check_drive_for_key()
usb_detector.USBDetector.check_drive_for_key (self, drive_path)
Check if a drive contains a private key file and load it if found.
Args:
    drive_path (str): Path to the drive to check
Definition at line 53 of file usb_detector.py.
References status_update, and usb_connected.
Referenced by run().
get_removable_drives()
usb_detector.USBDetector.get_removable_drives (self)
Get a list of removable drives.
Returns:
    list: List of drive paths
Definition at line 70 of file usb_detector.py.
References status_update, and system.
Referenced by run().
run()
usb_detector.USBDetector.run (self)
Main thread loop for monitoring USB drives.
Definition at line 27 of file usb_detector.py.
References check_drive_for_key(), connected_drives, get_removable_drives(), running, status_update, and usb_disconnected.
start_monitoring()
usb_detector.USBDetector.start_monitoring (self)
Start the monitoring thread.
Definition at line 120 of file usb_detector.py.
References running, and status_update.
stop_monitoring()
usb_detector.USBDetector.stop_monitoring (self)
Stop the monitoring thread.
Definition at line 112 of file usb_detector.py.
References running, and status_update.
Member Data Documentation
connected_drives
usb_detector.USBDetector.connected_drives = self.get_removable_drives()
Definition at line 24 of file usb_detector.py.
Referenced by run().
running
bool usb_detector.USBDetector.running = True
Definition at line 22 of file usb_detector.py.
Referenced by run(), start_monitoring(), and stop_monitoring().
status_update
usb_detector.USBDetector.status_update = pyqtSignal(str) static
Definition at line 18 of file usb_detector.py.
Referenced by check_drive_for_key(), get_removable_drives(), run(), start_monitoring(), and stop_monitoring().
system
str usb_detector.USBDetector.system = platform.system()
Definition at line 23 of file usb_detector.py.
Referenced by get_removable_drives().
usb_connected
usb_detector.USBDetector.usb_connected = pyqtSignal(str, bytes) static
Definition at line 16 of file usb_detector.py.
Referenced by check_drive_for_key().
usb_disconnected
usb_detector.USBDetector.usb_disconnected = pyqtSignal() static
Definition at line 17 of file usb_detector.py.
Referenced by run().
The documentation for this class was generated from the following file:
signature_app/usb_detector.py